# Generated by Django 4.2.20 on 2025-05-12 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app_devaru", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="date_sold",
            new_name="sale_date",
        ),
        migrations.AddField(
            model_name="jewelleryitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jewelleryitem",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="jewelleryitem",
            name="category",
            field=models.CharField(default="General", max_length=50),
        ),
        migrations.AlterField(
            model_name="jewelleryitem",
            name="description",
            field=models.TextField(blank=True, default="No description provided"),
        ),
        migrations.AlterField(
            model_name="jewelleryitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="jewelleryitem",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="sale",
            name="quantity_sold",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="sale",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
