# Generated by Django 4.2.20 on 2025-05-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_devaru", "0002_rename_date_sold_sale_sale_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="item",
        ),
        migrations.AddField(
            model_name="sale",
            name="customer_name",
            field=models.CharField(default="Unknown Customer", max_length=100),
        ),
        migrations.AddField(
            model_name="sale",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Paid", "Paid"),
                    ("Pending", "Pending"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="product_name",
            field=models.CharField(default="Unknown Product", max_length=100),
        ),
        migrations.AlterField(
            model_name="sale",
            name="quantity_sold",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="sale",
            name="sale_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="sale",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
