# Generated by Django 4.2.20 on 2025-05-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_devaru", "0003_remove_sale_item_sale_customer_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("product", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("Paid", "Paid"), ("Pending", "Pending")],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
