# Generated by Django 4.2.20 on 2025-05-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_devaru", "0004_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(default="N/A", max_length=15),
        ),
    ]
