# Generated by Django 4.2.20 on 2025-05-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_devaru", "0005_customer_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jewelleryitem",
            name="category",
        ),
        migrations.RemoveField(
            model_name="jewelleryitem",
            name="description",
        ),
        migrations.RemoveField(
            model_name="jewelleryitem",
            name="price",
        ),
        migrations.RemoveField(
            model_name="jewelleryitem",
            name="weight",
        ),
    ]
