# Generated by Django 4.2.20 on 2025-05-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_devaru", "0006_remove_jewelleryitem_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Gold", "Gold"),
                            ("Silver", "Silver"),
                            ("Platinum", "Platinum"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
    ]
