# Generated by Django 4.2.20 on 2025-05-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_devaru", "0007_item"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.RemoveField(
            model_name="jewelleryitem",
            name="created_at",
        ),
        migrations.AddField(
            model_name="jewelleryitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("Gold", "Gold"),
                    ("Silver", "Silver"),
                    ("Platinum", "Platinum"),
                ],
                default="Gold",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jewelleryitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
