# Generated by Django 4.2.20 on 2025-07-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_devaru", "0008_delete_item_remove_jewelleryitem_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="category",
            field=models.CharField(default="Gold", max_length=50),
            preserve_default=False,
        ),
    ]
