# Generated by Django 4.2.28 on 2026-06-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_devaru', '0009_customer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelleryitem',
            name='purity',
            field=models.CharField(default='22K', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jewelleryitem',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jewelleryitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
