# Generated by Django 4.2.28 on 2026-06-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_devaru', '0010_jewelleryitem_purity_jewelleryitem_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelleryitem',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
